#ifdef _OBJECTID
OBJECTID("%M%", "%I%", "20%E%", "%U%");
#endif /* _OBJECTID */
/*----------------------------------------------------------------------------|
|                                                                             |
|                              C Module                                       |
|                                                                             |
|-----------------------------------------------------------------------------|
|
| Ident        : %Z% %M%
| Author       : #generated by LACE#
| Description  : This module contains functions specific for logical action
|                'clean_area'.
|
| History      : Generated -> See target2code.trace
|
|-----------------------------------------------------------------------------|
|                                                                             |
|        Copyright (c) 2012, ASML Holding N.V. (including affiliates).        |
|                           All rights reserved                               |
|                                                                             |
|----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------|
|                           System Includes                                   |
|----------------------------------------------------------------------------*/

#include "string.h"

/*----------------------------------------------------------------------------|
|                           ASML Environment Includes                         |
|----------------------------------------------------------------------------*/

#include "ERXA/ERXA.h"
#include "PLXA/PLXA.h"
#include "PLXAxPTR/PLXAxPTR.h"
#include "SNXA/SNXAtyp.h"
#include "THxAOPxTRACE/THxAOPxTRACE_annotations.h"
#include "DDXAxOBJECT/DDXAxOBJECT.h"
#include "DDXAxVARARRAY/DDXAxVARARRAY.h"
#include "CNXA/CNXAtyp.h"

/*----------------------------------------------------------------------------|
|                           Other Components Includes                         |
|----------------------------------------------------------------------------*/
#include "WPxCHUCK/WPxCHUCKtyp.h"
#include "WPxSCANxDEF/WPxSCANxDEFtyp.h"
#include "asml/asmltyp.h"

/*----------------------------------------------------------------------------|
|                           Own Component Includes (Generated)                |
|----------------------------------------------------------------------------*/

#include "WTLANTxACTIONtyp.h"
#include "WTLANT_LA_clean_area.h"
#include "WTLANTXPXS.h"
#include "WTLANT_XStyp.h"
#include "WTLANTxERRtyp.h"
#include "WTLANTSDTF_clean_area.h"
#include "WTLANTxDECtyp.h"
#include "WTLANTxDEC_clean_area.h"
#include "WTLANTXS_DB.h"
/*----------------------------------------------------------------------------|
|                           Other Components Includes (Custom)                |
|----------------------------------------------------------------------------*/
/* This protected region can only be used as a temporary workaround for LACE limitations
and only with an explicit permission from the LACE team! */
/* PROTECTED REGION ID(WTLANT_LA_clean_area_headerIncludes) START */
/* PROTECTED REGION END */

/*----------------------------------------------------------------------------|
|                           Module Defines                                    |
|----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------|
|                           Module Type Definitions                           |
|----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------|
|                           Module Function Prototypes                        |
|----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------|
|                           Module Global data                                |
|----------------------------------------------------------------------------*/

static int gradual_cleaning_strategy_CA_cpcb(const int entry_id /*@unused@*/,
	const char * identifier /*@unused@*/,
	const WTLANTXS_sn_server_t sn_server /*@unused@*/,
	WTLANTXPXS_physical_result_data_t* res_data /*@unused@*/)
	/*#----------------------------------------------------------------------#*/
{
	int result = OK;
	/* Need to remove the starting dot ('.') in the iteration number string */
	const int iter_num = atoi(strrchr(identifier, '.') + 1);
	int result_stone_indefinitely;
	int result_stone_stop;
	/* Declare extra variables needed for internal results */
	WTLANTXPXS_physical_result_t other_action_result;

	/* Declare and read logical_action_data */
	WTLANTXPXS_logical_action_t logical_action_data;
	WTLANT_XS_PL2CL_clean_area_struct * const logical_action_p =
		&(logical_action_data.u.clean_area);
	(void) memset(&logical_action_data, 0, sizeof(WTLANTXPXS_logical_action_t));

	if (result == OK) {
		result = WTLANTXS_DB_get_logical_data(entry_id, &logical_action_data);
	}

	if (result == OK) {
		char other_action_id[WTLANTXPXS_MAX_IDENTIFIER_LENGTH] = "";

		(void) snprintf(other_action_id, sizeof other_action_id,
			"gradual_cleaning_strategy_CA.ssa_stone_indefinitly.%d",
			iter_num);

		result = WTLANTXS_DB_get_physical_result_by_id(entry_id,
			other_action_id, &other_action_result);

		result_stone_indefinitely =
			other_action_result.data.u.ssa_stone_indefinitly.result_stone_indefinitely;
	}

	if (result == OK) {
		char other_action_id[WTLANTXPXS_MAX_IDENTIFIER_LENGTH] = "";

		(void) snprintf(other_action_id, sizeof other_action_id,
			"gradual_cleaning_strategy_CA.ssa_stone_stop.%d", iter_num);

		result = WTLANTXS_DB_get_physical_result_by_id(entry_id,
			other_action_id, &other_action_result);

		result_stone_stop =
			other_action_result.data.u.ssa_stone_stop.result_stone_stop;
	}

	if (result == OK) {
		logical_action_p->output_buffer_gradual_cleaning_strategy_CA_result_stone_indefinitely[iter_num] =
			result_stone_indefinitely;
		logical_action_p->last_cond_val_gradual_cleaning_strategy_CA_result_stone_indefinitely =
			result_stone_indefinitely;
		logical_action_p->output_buffer_gradual_cleaning_strategy_CA_result_stone_stop[iter_num] =
			result_stone_stop;
		logical_action_p->last_cond_val_gradual_cleaning_strategy_CA_result_stone_stop =
			result_stone_stop;
		result = WTLANTXS_DB_set_logical_data(entry_id, &logical_action_data);
	}

	if (result != OK) {
		ERXA_LOG_ID(WTLANTxERR_LINKED_SYS_ERROR, result, &result,
			("Postprocessing callback function %s failed", __func__));
	}

	return result;
}

/*#----------------------------------------------------------------------#*/

static int gradual_cleaning_strategy_CA_polynomial_execution_gradual_strategy_CA_ppcb(
	const int entry_id /*@unused@*/,
	WTLANTXPXS_physical_request_t* params_ptr /*@unused@*/,
	WTLANTXPXS_physical_result_data_t* physical_result_ptr /*@unused@*/)
	/*#----------------------------------------------------------------------#*/
{
	int result = OK;
	WTLANTXPXS_physical_result_t previous_action_result;

	(void) memset(&previous_action_result, 0,
		sizeof(WTLANTXPXS_physical_result_t));

	/*---------------------------------------------------------------------
	| Declaration of buffers temporarily storing the output values of data 
	| transformation functions called in this function.
	|-------------------------------------------------------------------*/

	WTLANTxACTION_action_list* buf_gradual_cleaning_PA = NULL;
	int result_buf_gradual_cleaning_PA = OK; /* the result used for creation and destruction of the varible array */

	if (result == OK) {
		result = DDXAxOBJECT_full_create(WTLANTxACTION_ACTION_LIST_STR,
			(void **) &buf_gradual_cleaning_PA);
		result_buf_gradual_cleaning_PA = result;
	}

	WPxSCANxDEF_6dof_scan_params_struct buf_wp_scan_parameters;

	/* Declare and read logical_action_data */
	WTLANTXPXS_logical_action_t logical_action_data;
	WTLANT_XS_PL2CL_clean_area_struct * const logical_action_p =
		&(logical_action_data.u.clean_area);

	(void) memset(&logical_action_data, 0, sizeof(WTLANTXPXS_logical_action_t));

	if (result == OK) {
		result = WTLANTXS_DB_get_logical_data(entry_id, &logical_action_data);
	}

	if (result == OK) {
		result = DDXAxOBJECT_clone(WTLANTxACTION_ACTION_LIST_STR,
			(void*) &(logical_action_p->buf_gradual_cleaning_PA),
			(void**) &buf_gradual_cleaning_PA);
	}

	if (result == OK) {
		/* Need to remove the starting dot ('.') in the iteration number string */
		const int iter_num = atoi(strrchr(params_ptr->identifier, '.') + 1);

		result = WTLANTDTF_Cook_GC_polynomials_CA(
			&(buf_gradual_cleaning_PA->array[iter_num]) // for variable array 

			, &buf_wp_scan_parameters);
	}

	params_ptr->params.u.polynomial_execution_gradual_strategy_CA.wp_scan_parameters =
		buf_wp_scan_parameters;

	if (result_buf_gradual_cleaning_PA == OK) {
		result_buf_gradual_cleaning_PA = DDXAxOBJECT_full_destroy(
			WTLANTxACTION_ACTION_LIST_STR,
			(void **) &buf_gradual_cleaning_PA); /* this result is not handled yet */
	}

	if (result != OK) {
		ERXA_LOG_ID(WTLANTxERR_LINKED_SYS_ERROR, result, &result,
			("%s: Link error", __func__));
	}

	return result;
}

/*#----------------------------------------------------------------------#*/

static int gradual_cleaning_strategy_CA_ssa_stone_indefinitly_ppcb(
	const int entry_id /*@unused@*/,
	WTLANTXPXS_physical_request_t* params_ptr /*@unused@*/,
	WTLANTXPXS_physical_result_data_t* physical_result_ptr /*@unused@*/)
	/*#----------------------------------------------------------------------#*/
{
	int result = OK;
	WTLANTXPXS_physical_result_t previous_action_result;

	(void) memset(&previous_action_result, 0,
		sizeof(WTLANTXPXS_physical_result_t));

	/*---------------------------------------------------------------------
	| Declaration of buffers temporarily storing the output values of data 
	| transformation functions called in this function.
	|-------------------------------------------------------------------*/

	WTLANTxACTION_action_list* buf_gradual_cleaning_PA = NULL;
	int result_buf_gradual_cleaning_PA = OK; /* the result used for creation and destruction of the varible array */

	if (result == OK) {
		result = DDXAxOBJECT_full_create(WTLANTxACTION_ACTION_LIST_STR,
			(void **) &buf_gradual_cleaning_PA);
		result_buf_gradual_cleaning_PA = result;
	}

	int buf_rpm;

	/* Declare and read logical_action_data */
	WTLANTXPXS_logical_action_t logical_action_data;
	WTLANT_XS_PL2CL_clean_area_struct * const logical_action_p =
		&(logical_action_data.u.clean_area);

	(void) memset(&logical_action_data, 0, sizeof(WTLANTXPXS_logical_action_t));

	if (result == OK) {
		result = WTLANTXS_DB_get_logical_data(entry_id, &logical_action_data);
	}

	if (result == OK) {
		result = DDXAxOBJECT_clone(WTLANTxACTION_ACTION_LIST_STR,
			(void*) &(logical_action_p->buf_gradual_cleaning_PA),
			(void**) &buf_gradual_cleaning_PA);
	}

	if (result == OK) {
		/* Need to remove the starting dot ('.') in the iteration number string */
		const int iter_num = atoi(strrchr(params_ptr->identifier, '.') + 1);

		result = WTLANTDTF_Cook_GC_stone_rotation_command_CA(
			&(buf_gradual_cleaning_PA->array[iter_num]) // for variable array 

			, &buf_rpm);
	}

	params_ptr->params.u.ssa_stone_indefinitly.rpm = buf_rpm;

	if (result_buf_gradual_cleaning_PA == OK) {
		result_buf_gradual_cleaning_PA = DDXAxOBJECT_full_destroy(
			WTLANTxACTION_ACTION_LIST_STR,
			(void **) &buf_gradual_cleaning_PA); /* this result is not handled yet */
	}

	if (result != OK) {
		ERXA_LOG_ID(WTLANTxERR_LINKED_SYS_ERROR, result, &result,
			("%s: Link error", __func__));
	}

	return result;
}

/*#----------------------------------------------------------------------#*/

static int meander_cleaning_strategy_CA_polynomial_execution_meander_strategy_CA_ppcb(
	const int entry_id /*@unused@*/,
	WTLANTXPXS_physical_request_t* params_ptr /*@unused@*/,
	WTLANTXPXS_physical_result_data_t* physical_result_ptr /*@unused@*/)
	/*#----------------------------------------------------------------------#*/
{
	int result = OK;
	WTLANTXPXS_physical_result_t previous_action_result;

	(void) memset(&previous_action_result, 0,
		sizeof(WTLANTXPXS_physical_result_t));

	/*---------------------------------------------------------------------
	| Declaration of buffers temporarily storing the output values of data 
	| transformation functions called in this function.
	|-------------------------------------------------------------------*/

	WTLANTxACTION_action_list* buf_meandering_PA = NULL;
	int result_buf_meandering_PA = OK; /* the result used for creation and destruction of the varible array */

	if (result == OK) {
		result = DDXAxOBJECT_full_create(WTLANTxACTION_ACTION_LIST_STR,
			(void **) &buf_meandering_PA);
		result_buf_meandering_PA = result;
	}

	WPxSCANxDEF_6dof_scan_params_struct buf_wp_scan_parameters;

	/* Declare and read logical_action_data */
	WTLANTXPXS_logical_action_t logical_action_data;
	WTLANT_XS_PL2CL_clean_area_struct * const logical_action_p =
		&(logical_action_data.u.clean_area);

	(void) memset(&logical_action_data, 0, sizeof(WTLANTXPXS_logical_action_t));

	if (result == OK) {
		result = WTLANTXS_DB_get_logical_data(entry_id, &logical_action_data);
	}

	if (result == OK) {
		result = DDXAxOBJECT_clone(WTLANTxACTION_ACTION_LIST_STR,
			(void*) &(logical_action_p->buf_meandering_PA),
			(void**) &buf_meandering_PA);
	}

	if (result == OK) {
		/* Need to remove the starting dot ('.') in the iteration number string */
		const int iter_num = atoi(strrchr(params_ptr->identifier, '.') + 1);

		result = WTLANTDTF_Cook_meander_polynomials_CA(
			&(buf_meandering_PA->array[iter_num])  // for variable array 

			, &buf_wp_scan_parameters);
	}

	params_ptr->params.u.polynomial_execution_meander_strategy_CA.wp_scan_parameters =
		buf_wp_scan_parameters;

	if (result_buf_meandering_PA == OK) {
		result_buf_meandering_PA = DDXAxOBJECT_full_destroy(
			WTLANTxACTION_ACTION_LIST_STR, (void **) &buf_meandering_PA); /* this result is not handled yet */
	}

	if (result != OK) {
		ERXA_LOG_ID(WTLANTxERR_LINKED_SYS_ERROR, result, &result,
			("%s: Link error", __func__));
	}

	return result;
}

/*#----------------------------------------------------------------------#*/

int WTLANT_LA_clean_area_pl(
	const WTLANT_XS_PL_clean_area_struct *logical_request_p /*@unused@*//* PROTECTED REGION ID(WTLANT_LA_clean_area_pl_logical_request_p_variable_trace) ENABLED START *//*$IN$*//*$trace(TRUE)$*//* PROTECTED REGION END */,
	WTLANT_XS_PL2CL_clean_area_struct *logical_action_p /*@unused@*//* PROTECTED REGION ID(WTLANT_LA_clean_area_pl_logical_action_p_variable_trace) ENABLED START *//*$IN$*//*$trace(FALSE)$*//* PROTECTED REGION END */,
	WTLANTXPXS_prepare_physical_t *params_p /*@unused@*//* PROTECTED REGION ID(WTLANT_LA_clean_area_pl_params_p_variable_trace) ENABLED START *//*$OUT$*//*$trace(FALSE)$*//* PROTECTED REGION END */)

	/*  Description : Select and define physical actions for logical action
	*                'clean_area from interface WTLAxCLEAN'.
	*  In          : logical_request_p - input parameters from the external interface
	*                logical_action_p - data to be used in calculate logical phase
	*  Out         : params_p - parameters for physical actions
	*  Pre.Cond.   : Output pointers are not NULL.
	*/
{
	/*---------------------------------------------------------------------
	| Protection of a protected region is enabled by adding the keyword 
	| ENABLED to the commented line below, just before the START keyword. 
	| Removing the ENABLED keyword disables the protection.
	---------------------------------------------------------------------*/

	/* This protected region can only be changed as a temporary workaround for LACE limitations
	and only with an explicit permission from the LACE team! */
	/* PROTECTED REGION ID(WTLANT_LA_clean_area_pl) START */

	int result = OK;
	int pa_counter = 0; /* Counts the number of physical actions */

						/*---------------------------------------------------------------------
						| Declaration of buffers temporarily storing the output values of data 
						| transformation functions called in this prepare logical function:
						|-------------------------------------------------------------------*/
	WTLANTxACTION_action_list* buf_gradual_cleaning_PA = NULL;
	int result_buf_gradual_cleaning_PA = OK; /* the result used for creation and destruction of the varible array */

	if (result == OK) {
		result = DDXAxOBJECT_full_create(WTLANTxACTION_ACTION_LIST_STR,
			(void **) &buf_gradual_cleaning_PA);
		result_buf_gradual_cleaning_PA = result;
	}

	WTLANTxACTION_action_list* buf_meandering_PA = NULL;
	int result_buf_meandering_PA = OK; /* the result used for creation and destruction of the varible array */

	if (result == OK) {
		result = DDXAxOBJECT_full_create(WTLANTxACTION_ACTION_LIST_STR,
			(void **) &buf_meandering_PA);
		result_buf_meandering_PA = result;
	}

	ASML_bool buf_pre_conditions_met;

	WPxSCANxDEF_6dof_scan_params_struct buf_wp_scan_parameters;

	/*---------------------------------------------------------------------
	| Fill the array of physical actions:
	|-------------------------------------------------------------------*/

	if (result == OK) {
		result = WTLANTDTF_Check_pre_conditions_CA(
			logical_request_p->area_diameter, logical_request_p->area_pos,
			logical_request_p->chuck_id, &buf_pre_conditions_met);
	}

	if (result == OK) {
		result = WTLANTDTF_Determine_start_position_of_cleaning_CA(
			logical_request_p->area_diameter, logical_request_p->area_pos,
			logical_request_p->chuck_id, &buf_wp_scan_parameters);
	}

	if (result == OK) {
		WTLANTXPXS_physical_request_t* const temp_physical_params_p =
			&(params_p->action_array[pa_counter]);

		(void) PLXAstr_strlcpy(temp_physical_params_p->identifier,
			"Go_to_extend_position_CA.847882045_1",
			sizeof(temp_physical_params_p->identifier));
		(void) PLXAstr_strlcpy(temp_physical_params_p->next_action_identifier,
			"ssa_enable_mmdc.847882045_2",
			sizeof(temp_physical_params_p->next_action_identifier));

		/*---------------------------------------------------------------------
		| Fill in remaining properties:
		---------------------------------------------------------------------*/
		temp_physical_params_p->params.u.Go_to_extend_position_CA.scan_timing.prep_time =
			0.0;
		temp_physical_params_p->params.u.Go_to_extend_position_CA.scan_timing.scan_time =
			0.0;
		temp_physical_params_p->physical_action_type =
			WTLANTXPXS_PHYS_GO_TO_EXTEND_POSITION_CA;
		temp_physical_params_p->wait_for_result = FALSE;
		/*TICS -6.3.2.2.a Conversion of pointer type to PLXAxPTR type */
		temp_physical_params_p->pp_function_ptr = PLXAxPTR_C_to_data_ptr(
			(void *) NULL);
		temp_physical_params_p->cp_function_ptr = PLXAxPTR_C_to_data_ptr(
			(void *) NULL);
		/*TICS +6.3.2.2.a */
		temp_physical_params_p->params.u.Go_to_extend_position_CA.wp_scan_parameters =
			buf_wp_scan_parameters;

		temp_physical_params_p->params.u.Go_to_extend_position_CA.chuck_id =
			logical_request_p->chuck_id;

		/*---------------------------------------------------------------------
		| Add the scan type to the physical parameters structure:
		---------------------------------------------------------------------*/
		temp_physical_params_p->params.u.Go_to_extend_position_CA.scan_type =
			SNXA_NUMBERED_SCAN;

		pa_counter++;
	}

	if (result == OK) {
		WTLANTXPXS_physical_request_t* const temp_physical_params_p =
			&(params_p->action_array[pa_counter]);

		(void) PLXAstr_strlcpy(temp_physical_params_p->identifier,
			"ssa_enable_mmdc.847882045_2",
			sizeof(temp_physical_params_p->identifier));
		(void) PLXAstr_strlcpy(temp_physical_params_p->next_action_identifier,
			"ssa_extend_stone.847882045_3",
			sizeof(temp_physical_params_p->next_action_identifier));

		/*---------------------------------------------------------------------
		| Fill in remaining properties:
		---------------------------------------------------------------------*/
		temp_physical_params_p->params.u.ssa_enable_mmdc.scan_timing.prep_time =
			0.0;
		temp_physical_params_p->params.u.ssa_enable_mmdc.scan_timing.scan_time =
			0.0;
		temp_physical_params_p->physical_action_type =
			WTLANTXPXS_PHYS_SSA_ENABLE_MMDC;
		temp_physical_params_p->wait_for_result = FALSE;
		/*TICS -6.3.2.2.a Conversion of pointer type to PLXAxPTR type */
		temp_physical_params_p->pp_function_ptr = PLXAxPTR_C_to_data_ptr(
			(void *) NULL);
		temp_physical_params_p->cp_function_ptr = PLXAxPTR_C_to_data_ptr(
			(void *) NULL);
		/*TICS +6.3.2.2.a */
		temp_physical_params_p->params.u.ssa_enable_mmdc.chuck_id =
			logical_request_p->chuck_id;

		/*---------------------------------------------------------------------
		| Add the scan type to the physical parameters structure:
		---------------------------------------------------------------------*/
		temp_physical_params_p->params.u.ssa_enable_mmdc.scan_type =
			SNXA_NOT_A_SCAN;

		pa_counter++;
	}

	if (result == OK) {
		WTLANTXPXS_physical_request_t* const temp_physical_params_p =
			&(params_p->action_array[pa_counter]);

		(void) PLXAstr_strlcpy(temp_physical_params_p->identifier,
			"ssa_extend_stone.847882045_3",
			sizeof(temp_physical_params_p->identifier));
		(void) PLXAstr_strlcpy(temp_physical_params_p->next_action_identifier,
			"cleaning_strategy_selection",
			sizeof(temp_physical_params_p->next_action_identifier));

		/*---------------------------------------------------------------------
		| Fill in remaining properties:
		---------------------------------------------------------------------*/
		temp_physical_params_p->params.u.ssa_extend_stone.scan_timing.prep_time =
			0.0;
		temp_physical_params_p->params.u.ssa_extend_stone.scan_timing.scan_time =
			0.0;
		temp_physical_params_p->physical_action_type =
			WTLANTXPXS_PHYS_SSA_EXTEND_STONE;
		temp_physical_params_p->wait_for_result = FALSE;
		/*TICS -6.3.2.2.a Conversion of pointer type to PLXAxPTR type */
		temp_physical_params_p->pp_function_ptr = PLXAxPTR_C_to_data_ptr(
			(void *) NULL);
		temp_physical_params_p->cp_function_ptr = PLXAxPTR_C_to_data_ptr(
			(void *) NULL);
		/*TICS +6.3.2.2.a */

		/*---------------------------------------------------------------------
		| Add the scan type to the physical parameters structure:
		---------------------------------------------------------------------*/
		temp_physical_params_p->params.u.ssa_extend_stone.scan_type =
			SNXA_NOT_A_SCAN;

		pa_counter++;
	}

	if (result == OK) {

		/* We have to make a decision here. */
		WTLANTxDEC_clean_area_cleaning_strategy_selection_enum_t cleaning_strategy_selection_result;

		if (result == OK) {
			result = WTLANTxDEC_clean_area_cleaning_strategy_selection_decision(
				&cleaning_strategy_selection_result);
		}

		logical_action_p->cleaning_strategy_selection_result =
			cleaning_strategy_selection_result;
		switch (logical_action_p->cleaning_strategy_selection_result) {
		case (WTLANTxDEC_CLEAN_AREA_CLEANING_STRATEGY_SELECTION_MEANDER_CLEANING_STRATEGY):

			/* Make the previous action to reference to this clause. */
			if (pa_counter > 0) {
				(void) PLXAstr_strlcpy(
					params_p->action_array[pa_counter - 1].next_action_identifier,
					"meander_cleaning_strategy_CA.polynomial_execution_meander_strategy_CA.0",
					sizeof(params_p->action_array[pa_counter - 1].next_action_identifier));
			}

			if (result == OK) {
				result = WTLANTDTF_Generate_meander_cleaning_PA_CA(
					logical_request_p->area_diameter,
					logical_request_p->area_pos,
					logical_request_p->chuck_id, buf_meandering_PA);
			}

			if (result == OK) {
				int nr_iterations = 0;

				/* Declaration of the local input buffer */
				const WTLANTxACTION_action_list_t *iter_ptr = NULL;

				nr_iterations = buf_meandering_PA->len;

				if (nr_iterations
						> WTLANT_XS_MAX_NR_ITERATIONS_MEANDER_CLEANING_STRATEGY_CA) {
					ERXA_ROOT_LOG_ID(result, WTLANTxERR_SYS_ERR,
						("Exceeded maximum number of iterations. Allowed: %d, Defined: %d.", WTLANT_XS_MAX_NR_ITERATIONS_MEANDER_CLEANING_STRATEGY_CA, nr_iterations));
				}

				if (result == OK) {
					int meander_cleaning_strategy_CA_counter = 0;

					for (;
						meander_cleaning_strategy_CA_counter < nr_iterations
						&& (result == OK);
						meander_cleaning_strategy_CA_counter++) {

						/* Create reference to the ith element of the input vararray */
						result = DDXAxVARARRAY_GET_REF(
							WTLANTxACTION_ACTION_LIST_STR,
							*(buf_meandering_PA),
							meander_cleaning_strategy_CA_counter, iter_ptr);

						if (result == OK) {
							WTLANTXPXS_physical_request_t* const temp_physical_params_p =
								&(params_p->action_array[pa_counter]);

							(void) PLXAstr_snprintf(
								temp_physical_params_p->identifier,
								sizeof(temp_physical_params_p->identifier),
								"meander_cleaning_strategy_CA.polynomial_execution_meander_strategy_CA.%d",
								meander_cleaning_strategy_CA_counter);

							(void) PLXAstr_snprintf(
								temp_physical_params_p->next_action_identifier,
								sizeof(temp_physical_params_p->next_action_identifier),
								"meander_cleaning_strategy_CA.polynomial_execution_meander_strategy_CA.%d",
								meander_cleaning_strategy_CA_counter + 1);

							/*---------------------------------------------------------------------
							| Fill in remaining properties:
							---------------------------------------------------------------------*/
							temp_physical_params_p->params.u.polynomial_execution_meander_strategy_CA.scan_timing.prep_time =
								0.0;
							temp_physical_params_p->params.u.polynomial_execution_meander_strategy_CA.scan_timing.scan_time =
								0.0;
							temp_physical_params_p->physical_action_type =
								WTLANTXPXS_PHYS_POLYNOMIAL_EXECUTION_MEANDER_STRATEGY_CA;
							temp_physical_params_p->wait_for_result = FALSE;
							/*TICS -6.3.2.2.a Conversion of pointer type to PLXAxPTR type */
							temp_physical_params_p->pp_function_ptr =
								PLXAxPTR_C_to_data_ptr(
								(void *) meander_cleaning_strategy_CA_polynomial_execution_meander_strategy_CA_ppcb);
							temp_physical_params_p->cp_function_ptr =
								PLXAxPTR_C_to_data_ptr((void *) NULL);
							/*TICS +6.3.2.2.a */

							temp_physical_params_p->params.u.polynomial_execution_meander_strategy_CA.chuck_id =
								logical_request_p->chuck_id;

							/*---------------------------------------------------------------------
							| Add the scan type to the physical parameters structure:
							---------------------------------------------------------------------*/
							temp_physical_params_p->params.u.polynomial_execution_meander_strategy_CA.scan_type =
								SNXA_NUMBERED_SCAN;

							pa_counter++;
						}
					}

					/* Overrule the value of the last element in the loop to refer to the correct next action */
					if (result == OK) {
						(void) PLXAstr_strlcpy(
							params_p->action_array[pa_counter - 1].next_action_identifier,
							"ssa_retract_stone.847882045_8",
							sizeof(params_p->action_array[pa_counter - 1].next_action_identifier));

					}

					/* Store number of iterations in the logical action data */
					logical_action_p->nr_iterations_meander_cleaning_strategy_CA =
						nr_iterations;
				}
			}
			break;
		case (WTLANTxDEC_CLEAN_AREA_CLEANING_STRATEGY_SELECTION_GRADUAL_CLEANING_STRATEGY):

			/* Make the previous action to reference to this clause. */
			if (pa_counter > 0) {
				(void) PLXAstr_strlcpy(
					params_p->action_array[pa_counter - 1].next_action_identifier,
					"gradual_cleaning_strategy_CA.ssa_stone_indefinitly.0",
					sizeof(params_p->action_array[pa_counter - 1].next_action_identifier));
			}

			if (result == OK) {
				result = WTLANTDTF_Generate_gradual_cleaning_PA_CA(
					logical_request_p->area_diameter,
					logical_request_p->area_pos,
					logical_request_p->chuck_id, buf_gradual_cleaning_PA);
			}

			if (result == OK) {
				int nr_iterations = 0;

				/* Declaration of the local input buffer */
				const WTLANTxACTION_action_list_t *iter_ptr = NULL;

				nr_iterations = buf_gradual_cleaning_PA->len;

				if (nr_iterations
						> WTLANT_XS_MAX_NR_ITERATIONS_GRADUAL_CLEANING_STRATEGY_CA) {
					ERXA_ROOT_LOG_ID(result, WTLANTxERR_SYS_ERR,
						("Exceeded maximum number of iterations. Allowed: %d, Defined: %d.", WTLANT_XS_MAX_NR_ITERATIONS_GRADUAL_CLEANING_STRATEGY_CA, nr_iterations));
				}

				if (result == OK) {
					int gradual_cleaning_strategy_CA_counter = 0;

					for (;
						gradual_cleaning_strategy_CA_counter < nr_iterations
						&& (result == OK);
						gradual_cleaning_strategy_CA_counter++) {

						/* Create reference to the ith element of the input vararray */
						result = DDXAxVARARRAY_GET_REF(
							WTLANTxACTION_ACTION_LIST_STR,
							*(buf_gradual_cleaning_PA),
							gradual_cleaning_strategy_CA_counter, iter_ptr);

						if (result == OK) {
							WTLANTXPXS_physical_request_t* const temp_physical_params_p =
								&(params_p->action_array[pa_counter]);

							(void) PLXAstr_snprintf(
								temp_physical_params_p->identifier,
								sizeof(temp_physical_params_p->identifier),
								"gradual_cleaning_strategy_CA.ssa_stone_indefinitly.%d",
								gradual_cleaning_strategy_CA_counter);

							(void) PLXAstr_snprintf(
								temp_physical_params_p->next_action_identifier,
								sizeof(temp_physical_params_p->next_action_identifier),
								"gradual_cleaning_strategy_CA.polynomial_execution_gradual_strategy_CA.%d",
								gradual_cleaning_strategy_CA_counter);

							/*---------------------------------------------------------------------
							| Fill in remaining properties:
							---------------------------------------------------------------------*/
							temp_physical_params_p->params.u.ssa_stone_indefinitly.scan_timing.prep_time =
								0.0;
							temp_physical_params_p->params.u.ssa_stone_indefinitly.scan_timing.scan_time =
								0.0;
							temp_physical_params_p->physical_action_type =
								WTLANTXPXS_PHYS_SSA_STONE_INDEFINITLY;
							temp_physical_params_p->wait_for_result = FALSE;
							/*TICS -6.3.2.2.a Conversion of pointer type to PLXAxPTR type */
							temp_physical_params_p->pp_function_ptr =
								PLXAxPTR_C_to_data_ptr(
								(void *) gradual_cleaning_strategy_CA_ssa_stone_indefinitly_ppcb);
							temp_physical_params_p->cp_function_ptr =
								PLXAxPTR_C_to_data_ptr((void *) NULL);
							/*TICS +6.3.2.2.a */

							/*---------------------------------------------------------------------
							| Add the scan type to the physical parameters structure:
							---------------------------------------------------------------------*/
							temp_physical_params_p->params.u.ssa_stone_indefinitly.scan_type =
								SNXA_NOT_A_SCAN;

							pa_counter++;
						}

						if (result == OK) {
							WTLANTXPXS_physical_request_t* const temp_physical_params_p =
								&(params_p->action_array[pa_counter]);

							(void) PLXAstr_snprintf(
								temp_physical_params_p->identifier,
								sizeof(temp_physical_params_p->identifier),
								"gradual_cleaning_strategy_CA.polynomial_execution_gradual_strategy_CA.%d",
								gradual_cleaning_strategy_CA_counter);

							(void) PLXAstr_snprintf(
								temp_physical_params_p->next_action_identifier,
								sizeof(temp_physical_params_p->next_action_identifier),
								"gradual_cleaning_strategy_CA.ssa_stone_stop.%d",
								gradual_cleaning_strategy_CA_counter);

							/*---------------------------------------------------------------------
							| Fill in remaining properties:
							---------------------------------------------------------------------*/
							temp_physical_params_p->params.u.polynomial_execution_gradual_strategy_CA.scan_timing.prep_time =
								0.0;
							temp_physical_params_p->params.u.polynomial_execution_gradual_strategy_CA.scan_timing.scan_time =
								0.0;
							temp_physical_params_p->physical_action_type =
								WTLANTXPXS_PHYS_POLYNOMIAL_EXECUTION_GRADUAL_STRATEGY_CA;
							temp_physical_params_p->wait_for_result = FALSE;
							/*TICS -6.3.2.2.a Conversion of pointer type to PLXAxPTR type */
							temp_physical_params_p->pp_function_ptr =
								PLXAxPTR_C_to_data_ptr(
								(void *) gradual_cleaning_strategy_CA_polynomial_execution_gradual_strategy_CA_ppcb);
							temp_physical_params_p->cp_function_ptr =
								PLXAxPTR_C_to_data_ptr((void *) NULL);
							/*TICS +6.3.2.2.a */

							temp_physical_params_p->params.u.polynomial_execution_gradual_strategy_CA.chuck_id =
								logical_request_p->chuck_id;

							/*---------------------------------------------------------------------
							| Add the scan type to the physical parameters structure:
							---------------------------------------------------------------------*/
							temp_physical_params_p->params.u.polynomial_execution_gradual_strategy_CA.scan_type =
								SNXA_NUMBERED_SCAN;

							pa_counter++;
						}

						if (result == OK) {
							WTLANTXPXS_physical_request_t* const temp_physical_params_p =
								&(params_p->action_array[pa_counter]);

							(void) PLXAstr_snprintf(
								temp_physical_params_p->identifier,
								sizeof(temp_physical_params_p->identifier),
								"gradual_cleaning_strategy_CA.ssa_stone_stop.%d",
								gradual_cleaning_strategy_CA_counter);

							(void) PLXAstr_snprintf(
								temp_physical_params_p->next_action_identifier,
								sizeof(temp_physical_params_p->next_action_identifier),
								"gradual_cleaning_strategy_CA.ssa_stone_indefinitly.%d",
								gradual_cleaning_strategy_CA_counter + 1);

							/*---------------------------------------------------------------------
							| Fill in remaining properties:
							---------------------------------------------------------------------*/
							temp_physical_params_p->params.u.ssa_stone_stop.scan_timing.prep_time =
								0.0;
							temp_physical_params_p->params.u.ssa_stone_stop.scan_timing.scan_time =
								0.0;
							temp_physical_params_p->physical_action_type =
								WTLANTXPXS_PHYS_SSA_STONE_STOP;
							if (gradual_cleaning_strategy_CA_counter
								< nr_iterations - 1) {
								temp_physical_params_p->wait_for_result = FALSE;
							} else {
								temp_physical_params_p->wait_for_result = TRUE;
							}
							/*TICS -6.3.2.2.a Conversion of pointer type to PLXAxPTR type */
							temp_physical_params_p->pp_function_ptr =
								PLXAxPTR_C_to_data_ptr((void *) NULL);
							temp_physical_params_p->cp_function_ptr =
								PLXAxPTR_C_to_data_ptr(
								(void *) gradual_cleaning_strategy_CA_cpcb);
							/*TICS +6.3.2.2.a */

							/*---------------------------------------------------------------------
							| Add the scan type to the physical parameters structure:
							---------------------------------------------------------------------*/
							temp_physical_params_p->params.u.ssa_stone_stop.scan_type =
								SNXA_NOT_A_SCAN;

							pa_counter++;
						}
					}

					/* Overrule the value of the last element in the loop to refer to the correct next action */
					if (result == OK) {
						(void) PLXAstr_strlcpy(
							params_p->action_array[pa_counter - 1].next_action_identifier,
							"ssa_retract_stone.847882045_8",
							sizeof(params_p->action_array[pa_counter - 1].next_action_identifier));

					}

					/* Store number of iterations in the logical action data */
					logical_action_p->nr_iterations_gradual_cleaning_strategy_CA =
						nr_iterations;
				}
			}
			break;
		default:
			ERXA_ROOT_LOG_ID(result, WTLANTxERR_SYS_ERR,
				("Unknown decision choice %d for decision 'cleaning_strategy_selection'", logical_action_p->cleaning_strategy_selection_result));
			break;
		}
	}

	if (result == OK) {
		WTLANTXPXS_physical_request_t* const temp_physical_params_p =
			&(params_p->action_array[pa_counter]);

		(void) PLXAstr_strlcpy(temp_physical_params_p->identifier,
			"ssa_retract_stone.847882045_8",
			sizeof(temp_physical_params_p->identifier));
		(void) PLXAstr_strlcpy(temp_physical_params_p->next_action_identifier,
			"ssa_disable_mmdc.847882045_9",
			sizeof(temp_physical_params_p->next_action_identifier));

		/*---------------------------------------------------------------------
		| Fill in remaining properties:
		---------------------------------------------------------------------*/
		temp_physical_params_p->params.u.ssa_retract_stone.scan_timing.prep_time =
			0.0;
		temp_physical_params_p->params.u.ssa_retract_stone.scan_timing.scan_time =
			0.0;
		temp_physical_params_p->physical_action_type =
			WTLANTXPXS_PHYS_SSA_RETRACT_STONE;
		temp_physical_params_p->wait_for_result = FALSE;
		/*TICS -6.3.2.2.a Conversion of pointer type to PLXAxPTR type */
		temp_physical_params_p->pp_function_ptr = PLXAxPTR_C_to_data_ptr(
			(void *) NULL);
		temp_physical_params_p->cp_function_ptr = PLXAxPTR_C_to_data_ptr(
			(void *) NULL);
		/*TICS +6.3.2.2.a */

		/*---------------------------------------------------------------------
		| Add the scan type to the physical parameters structure:
		---------------------------------------------------------------------*/
		temp_physical_params_p->params.u.ssa_retract_stone.scan_type =
			SNXA_NOT_A_SCAN;

		pa_counter++;
	}

	if (result == OK) {
		WTLANTXPXS_physical_request_t* const temp_physical_params_p =
			&(params_p->action_array[pa_counter]);

		(void) PLXAstr_strlcpy(temp_physical_params_p->identifier,
			"ssa_disable_mmdc.847882045_9",
			sizeof(temp_physical_params_p->identifier));
		(void) PLXAstr_strlcpy(temp_physical_params_p->next_action_identifier,
			"", sizeof(temp_physical_params_p->next_action_identifier));

		/*---------------------------------------------------------------------
		| Fill in remaining properties:
		---------------------------------------------------------------------*/
		temp_physical_params_p->params.u.ssa_disable_mmdc.scan_timing.prep_time =
			0.0;
		temp_physical_params_p->params.u.ssa_disable_mmdc.scan_timing.scan_time =
			0.0;
		temp_physical_params_p->physical_action_type =
			WTLANTXPXS_PHYS_SSA_DISABLE_MMDC;
		temp_physical_params_p->wait_for_result = FALSE;
		/*TICS -6.3.2.2.a Conversion of pointer type to PLXAxPTR type */
		temp_physical_params_p->pp_function_ptr = PLXAxPTR_C_to_data_ptr(
			(void *) NULL);
		temp_physical_params_p->cp_function_ptr = PLXAxPTR_C_to_data_ptr(
			(void *) NULL);
		/*TICS +6.3.2.2.a */
		temp_physical_params_p->params.u.ssa_disable_mmdc.chuck_id =
			logical_request_p->chuck_id;

		/*---------------------------------------------------------------------
		| Add the scan type to the physical parameters structure:
		---------------------------------------------------------------------*/
		temp_physical_params_p->params.u.ssa_disable_mmdc.scan_type =
			SNXA_NOT_A_SCAN;

		pa_counter++;
	}

	if (pa_counter > WTLANT_XS_NR_PHYS_ACT_MAX) {
		ERXA_ROOT_LOG_ID(result, WTLANTxERR_SYS_ERR,
			("Exceeded maximum number of physical actions per logical action. Allowed: %d, Defined: %d.", WTLANT_XS_NR_PHYS_ACT_MAX, pa_counter));
	}

	/* The number of actions is equal to pa_counter (due to pa_counter++) */
	params_p->nr_actions = pa_counter;

	/*---------------------------------------------------------------------
	| Copy logical action data needed later on in   
	| _pp or in the calculate logical phase:
	|-------------------------------------------------------------------*/

	if (result == OK) {
		result = DDXAxOBJECT_sub_clone(WTLANTxACTION_ACTION_LIST_STR,
			(void*) buf_gradual_cleaning_PA,
			&(logical_action_p->buf_gradual_cleaning_PA));
	}

	if (result == OK) {
		result = DDXAxOBJECT_sub_clone(WTLANTxACTION_ACTION_LIST_STR,
			(void*) buf_meandering_PA,
			&(logical_action_p->buf_meandering_PA));
	}
	logical_action_p->buf_pre_conditions_met = buf_pre_conditions_met;

	if (result_buf_gradual_cleaning_PA == OK) {
		result_buf_gradual_cleaning_PA = DDXAxOBJECT_full_destroy(
			WTLANTxACTION_ACTION_LIST_STR,
			(void **) &buf_gradual_cleaning_PA); /* this result is not handled yet */
	}

	if (result_buf_meandering_PA == OK) {
		result_buf_meandering_PA = DDXAxOBJECT_full_destroy(
			WTLANTxACTION_ACTION_LIST_STR, (void **) &buf_meandering_PA); /* this result is not handled yet */
	}

	/* PROTECTED REGION END */
	return result;
}

/*#----------------------------------------------------------------------#*/

int WTLANT_LA_clean_area_cl(
	const WTLANTXPXS_physical_result_t* physical_results_p /*@unused@*//* PROTECTED REGION ID(WTLANT_LA_clean_area_cl_physical_results_p_variable_trace) ENABLED START *//*$IN$*//*$trace(FALSE)$*//* PROTECTED REGION END */,
	const int nr_physical_results /*@unused@*/,
	const WTLANT_XS_PL2CL_clean_area_struct* logical_action_p /*@unused@*//* PROTECTED REGION ID(WTLANT_LA_clean_area_cl_logical_action_p_variable_trace) ENABLED START *//*$IN$*//*$trace(FALSE)$*//* PROTECTED REGION END */)

	/*  Description : This function contains component specific calculate logical result functionality
	*  In          : physical_results_p - Data structure containing all the physical action results
	*              : nr_physical_results - Indicates the number of physical action results
	*              : logical_action_p - Pointer to the prepared logical action data
	*  InOut       : -
	*  Out         : logical_result_p - Data structure containing the logical action result
	*/
{
	/*---------------------------------------------------------------------
	| Protection of a protected region is enabled by adding the keyword 
	| ENABLED to the commented line below, just before the START keyword. 
	| Removing the ENABLED keyword disables the protection.
	---------------------------------------------------------------------*/
	/* This protected region can only be changed as a temporary workaround for LACE limitations
	and only with an explicit permission from the LACE team! */
	/*PROTECTED REGION ID(WTLANT_LA_clean_area_cl) START*/

	int result = OK;
	/*---------------------------------------------------------------------
	| Local variables temporarily storing the physical results retrieved
	| from the array of physical action results.
	---------------------------------------------------------------------*/
	int result_disable_mmdc;
	int result_enable_mmdc;
	int result_extend_stone;
	int result_retract_stone;

	/*---------------------------------------------------------------------
	| Initialize all local variables
	---------------------------------------------------------------------*/
	(void) memset(&result_disable_mmdc, 0, sizeof(int));
	(void) memset(&result_enable_mmdc, 0, sizeof(int));
	(void) memset(&result_extend_stone, 0, sizeof(int));
	(void) memset(&result_retract_stone, 0, sizeof(int));

	if (result == OK) {
		const WTLANTXPXS_physical_result_t * const temp_physical_result_p =
			WTLANTXPXS_lookup_physical_result(nr_physical_results,
				physical_results_p, "ssa_disable_mmdc.847882045_9");

		if (temp_physical_result_p != NULL) {
			result_disable_mmdc =
				temp_physical_result_p->data.u.ssa_disable_mmdc.result_disable_mmdc;
		} else {
			ERXA_ROOT_LOG_ID(result, WTLANTxERR_SYS_ERR,
				("Physical action results store does not contain any result for action with id: %s", "ssa_disable_mmdc.847882045_9"));
		}
	}

	if (result == OK) {
		const WTLANTXPXS_physical_result_t * const temp_physical_result_p =
			WTLANTXPXS_lookup_physical_result(nr_physical_results,
				physical_results_p, "ssa_enable_mmdc.847882045_2");

		if (temp_physical_result_p != NULL) {
			result_enable_mmdc =
				temp_physical_result_p->data.u.ssa_enable_mmdc.result_enable_mmdc;
		} else {
			ERXA_ROOT_LOG_ID(result, WTLANTxERR_SYS_ERR,
				("Physical action results store does not contain any result for action with id: %s", "ssa_enable_mmdc.847882045_2"));
		}
	}

	if (result == OK) {
		const WTLANTXPXS_physical_result_t * const temp_physical_result_p =
			WTLANTXPXS_lookup_physical_result(nr_physical_results,
				physical_results_p, "ssa_extend_stone.847882045_3");

		if (temp_physical_result_p != NULL) {
			result_extend_stone =
				temp_physical_result_p->data.u.ssa_extend_stone.result_extend_stone;
		} else {
			ERXA_ROOT_LOG_ID(result, WTLANTxERR_SYS_ERR,
				("Physical action results store does not contain any result for action with id: %s", "ssa_extend_stone.847882045_3"));
		}
	}

	if (result == OK) {
		const WTLANTXPXS_physical_result_t * const temp_physical_result_p =
			WTLANTXPXS_lookup_physical_result(nr_physical_results,
				physical_results_p, "ssa_retract_stone.847882045_8");

		if (temp_physical_result_p != NULL) {
			result_retract_stone =
				temp_physical_result_p->data.u.ssa_retract_stone.result_retract_stone;
		} else {
			ERXA_ROOT_LOG_ID(result, WTLANTxERR_SYS_ERR,
				("Physical action results store does not contain any result for action with id: %s", "ssa_retract_stone.847882045_8"));
		}
	}

	/*---------------------------------------------------------------------
	| Calculate the logical result:
	---------------------------------------------------------------------*/

	if (result == OK) {
		result =
			WTLANTDTF_Check_post_conditions_CA(
				logical_action_p->nr_iterations_gradual_cleaning_strategy_CA,
				&logical_action_p->output_buffer_gradual_cleaning_strategy_CA_result_stone_indefinitely[0],
				logical_action_p->nr_iterations_gradual_cleaning_strategy_CA,
				&logical_action_p->output_buffer_gradual_cleaning_strategy_CA_result_stone_stop[0],
				logical_action_p->buf_pre_conditions_met,
				result_disable_mmdc, result_enable_mmdc,
				result_extend_stone, result_retract_stone);
	}

	/*PROTECTED REGION END*/
	return result;
}

/*#----------------------------------------------------------------------#*/

int WTLANT_LA_clean_area_cleanup_action(
	const WTLANTXPXS_logical_action_t *logical_action_p /*@unused@*//*$trace(FALSE)$*/)

	/*  Description : This function contains component specific cleanup logical action functionality
	*  In          : logical_action_p - Identifies the logical action to be cleaned up
	*  Returns     : OK
	*  Notes       : Currently, no functionality required. OK is returned.
	*/
{
	return OK;
} /* End <WTLANT_LA_clean_area_cleanup_action> */

  /*#-------------------------------------------------------------------------#*/

int WTLANT_LA_clean_area_cleanup_result(
	WTLANTXPXS_logical_result_t *logical_result_p /*@unused@*//*$trace(FALSE)$*/)

	/*  Description : This function contains component specific cleanup logical result functionality
	*  In          : logical_result_p - Identifies the logical result to be cleaned up
	*  Returns     : OK or error
	*  Notes       : -
	*/
{
	return OK;
} /* End <WTLANT_LA_clean_area_cleanup_result> */
  /*#-------------------------------------------------------------------------#*/

  /*#---------------------------- End of File --------------------------------#*/
